name: Flat

on:
  push:
    branches: [ main ]
  workflow_dispatch: {}
  schedule:
    - cron: '*/5 * * * *'   # каждые 5 минут (UTC)

permissions:
  contents: write           # разрешаем push

concurrency:
  group: flat-sync          # чтоб не толкались параллельные запуски
  cancel-in-progress: false

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          persist-credentials: true

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      - name: Install deps
        run: |
          python -m venv venv
          source venv/bin/activate
          pip install -r requirements.txt
          pip install playwright==1.40.0
          python -m playwright install --with-deps

      - name: Generate RSS
        env:
          MS_TOKEN: ${{ secrets.MS_TOKEN }}
        run: |
          source venv/bin/activate
          python postprocessing.py

      - name: Commit & push if changed
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"

          # убедим remоte использовать токен
          git remote set-url origin \
            https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }}.git

          git add -A
          if git diff --cached --quiet; then
            echo "No changes to commit"
            exit 0
          fi

          # защищаемся от non-fast-forward
          git pull --rebase --autostash
          git commit -m "Latest TikTok RSS"
          git push
